export function nationalities() {
    return [
      { label: 'Afghanistan', value: 'https://flagcdn.com/af.svg' },
      { label: 'Åland Islands', value: 'https://flagcdn.com/ax.svg' },
      { label: 'Albania', value: 'https://flagcdn.com/al.svg' },
      { label: 'Algeria', value: 'https://flagcdn.com/dz.svg' },
      { label: 'American Samoa', value: 'https://flagcdn.com/as.svg' },
      { label: 'Andorra', value: 'https://flagcdn.com/ad.svg' },
      { label: 'Angola', value: 'https://flagcdn.com/ao.svg' },
      { label: 'Anguilla', value: 'https://flagcdn.com/ai.svg' },
      { label: 'Antarctica', value: 'https://flagcdn.com/aq.svg' },
      { label: 'Antigua and Barbuda', value: 'https://flagcdn.com/ag.svg' },
      { label: 'Argentina', value: 'https://flagcdn.com/ar.svg' },
      { label: 'Armenia', value: 'https://flagcdn.com/am.svg' },
      { label: 'Aruba', value: 'https://flagcdn.com/aw.svg' },
      { label: 'Australia', value: 'https://flagcdn.com/au.svg' },
      { label: 'Austria', value: 'https://flagcdn.com/at.svg' },
      { label: 'Azerbaijan', value: 'https://flagcdn.com/az.svg' },
      { label: 'Bahamas', value: 'https://flagcdn.com/bs.svg' },
      { label: 'Bahrain', value: 'https://flagcdn.com/bh.svg' },
      { label: 'Bangladesh', value: 'https://flagcdn.com/bd.svg' },
      { label: 'Barbados', value: 'https://flagcdn.com/bb.svg' },
      { label: 'Belarus', value: 'https://flagcdn.com/by.svg' },
      { label: 'Belgium', value: 'https://flagcdn.com/be.svg' },
      { label: 'Belize', value: 'https://flagcdn.com/bz.svg' },
      { label: 'Benin', value: 'https://flagcdn.com/bj.svg' },
      { label: 'Bermuda', value: 'https://flagcdn.com/bm.svg' },
      { label: 'Bhutan', value: 'https://flagcdn.com/bt.svg' },
      {
        label: 'Bolivia (Plurinational State of)',
        value: 'https://flagcdn.com/bo.svg',
      },
      {
        label: 'Bonaire, Sint Eustatius and Saba',
        value: 'https://flagcdn.com/bq.svg',
      },
      { label: 'Bosnia and Herzegovina', value: 'https://flagcdn.com/ba.svg' },
      { label: 'Botswana', value: 'https://flagcdn.com/bw.svg' },
      { label: 'Bouvet Island', value: 'https://flagcdn.com/bv.svg' },
      { label: 'Brazil', value: 'https://flagcdn.com/br.svg' },
      {
        label: 'British Indian Ocean Territory',
        value: 'https://flagcdn.com/io.svg',
      },
      { label: 'Brunei Darussalam', value: 'https://flagcdn.com/bn.svg' },
      { label: 'Bulgaria', value: 'https://flagcdn.com/bg.svg' },
      { label: 'Burkina Faso', value: 'https://flagcdn.com/bf.svg' },
      { label: 'Burundi', value: 'https://flagcdn.com/bi.svg' },
      { label: 'Cabo Verde', value: 'https://flagcdn.com/cv.svg' },
      { label: 'Cambodia', value: 'https://flagcdn.com/kh.svg' },
      { label: 'Cameroon', value: 'https://flagcdn.com/cm.svg' },
      { label: 'Canada', value: 'https://flagcdn.com/ca.svg' },
      { label: 'Cayman Islands', value: 'https://flagcdn.com/ky.svg' },
      { label: 'Central African Republic', value: 'https://flagcdn.com/cf.svg' },
      { label: 'Chad', value: 'https://flagcdn.com/td.svg' },
      { label: 'Chile', value: 'https://flagcdn.com/cl.svg' },
      { label: 'China', value: 'https://flagcdn.com/cn.svg' },
      { label: 'Christmas Island', value: 'https://flagcdn.com/cx.svg' },
      { label: 'Cocos (Keeling) Islands', value: 'https://flagcdn.com/cc.svg' },
      { label: 'Colombia', value: 'https://flagcdn.com/co.svg' },
      { label: 'Comoros', value: 'https://flagcdn.com/km.svg' },
      { label: 'Congo', value: 'https://flagcdn.com/cg.svg' },
      {
        label: 'Congo, Democratic Republic of the',
        value: 'https://flagcdn.com/cd.svg',
      },
      { label: 'Cook Islands', value: 'https://flagcdn.com/ck.svg' },
      { label: 'Costa Rica', value: 'https://flagcdn.com/cr.svg' },
      { label: "Côte d'Ivoire", value: 'https://flagcdn.com/ci.svg' },
      { label: 'Croatia', value: 'https://flagcdn.com/hr.svg' },
      { label: 'Cuba', value: 'https://flagcdn.com/cu.svg' },
      { label: 'Curaçao', value: 'https://flagcdn.com/cw.svg' },
      { label: 'Cyprus', value: 'https://flagcdn.com/cy.svg' },
      { label: 'Czechia', value: 'https://flagcdn.com/cz.svg' },
      { label: 'Denmark', value: 'https://flagcdn.com/dk.svg' },
      { label: 'Djibouti', value: 'https://flagcdn.com/dj.svg' },
      { label: 'Dominica', value: 'https://flagcdn.com/dm.svg' },
      { label: 'Dominican Republic', value: 'https://flagcdn.com/do.svg' },
      { label: 'Ecuador', value: 'https://flagcdn.com/ec.svg' },
      { label: 'Egypt', value: 'https://flagcdn.com/eg.svg' },
      { label: 'El Salvador', value: 'https://flagcdn.com/sv.svg' },
      { label: 'Equatorial Guinea', value: 'https://flagcdn.com/gq.svg' },
      { label: 'Eritrea', value: 'https://flagcdn.com/er.svg' },
      { label: 'Estonia', value: 'https://flagcdn.com/ee.svg' },
      { label: 'Eswatini', value: 'https://flagcdn.com/sz.svg' },
      { label: 'Ethiopia', value: 'https://flagcdn.com/et.svg' },
      {
        label: 'Falkland Islands (Malvinas)',
        value: 'https://flagcdn.com/fk.svg',
      },
      { label: 'Faroe Islands', value: 'https://flagcdn.com/fo.svg' },
      { label: 'Fiji', value: 'https://flagcdn.com/fj.svg' },
      { label: 'Finland', value: 'https://flagcdn.com/fi.svg' },
      { label: 'France', value: 'https://flagcdn.com/fr.svg' },
      { label: 'French Guiana', value: 'https://flagcdn.com/gf.svg' },
      { label: 'French Polynesia', value: 'https://flagcdn.com/pf.svg' },
      {
        label: 'French Southern Territories',
        value: 'https://flagcdn.com/tf.svg',
      },
      { label: 'Gabon', value: 'https://flagcdn.com/ga.svg' },
      { label: 'Gambia', value: 'https://flagcdn.com/gm.svg' },
      { label: 'Georgia', value: 'https://flagcdn.com/ge.svg' },
      { label: 'Germany', value: 'https://flagcdn.com/de.svg' },
      { label: 'Ghana', value: 'https://flagcdn.com/gh.svg' },
      { label: 'Gibraltar', value: 'https://flagcdn.com/gi.svg' },
      { label: 'Greece', value: 'https://flagcdn.com/gr.svg' },
      { label: 'Greenland', value: 'https://flagcdn.com/gl.svg' },
      { label: 'Grenada', value: 'https://flagcdn.com/gd.svg' },
      { label: 'Guadeloupe', value: 'https://flagcdn.com/gp.svg' },
      { label: 'Guam', value: 'https://flagcdn.com/gu.svg' },
      { label: 'Guatemala', value: 'https://flagcdn.com/gt.svg' },
      { label: 'Guernsey', value: 'https://flagcdn.com/gg.svg' },
      { label: 'Guinea', value: 'https://flagcdn.com/gn.svg' },
      { label: 'Guinea-Bissau', value: 'https://flagcdn.com/gw.svg' },
      { label: 'Guyana', value: 'https://flagcdn.com/gy.svg' },
      { label: 'Haiti', value: 'https://flagcdn.com/ht.svg' },
      {
        label: 'Heard Island and McDonald Islands',
        value: 'https://flagcdn.com/hm.svg',
      },
      { label: 'Holy See', value: 'https://flagcdn.com/va.svg' },
      { label: 'Honduras', value: 'https://flagcdn.com/hn.svg' },
      { label: 'Hong Kong', value: 'https://flagcdn.com/hk.svg' },
      { label: 'Hungary', value: 'https://flagcdn.com/hu.svg' },
      { label: 'Iceland', value: 'https://flagcdn.com/is.svg' },
      { label: 'India', value: 'https://flagcdn.com/in.svg' },
      { label: 'Indonesia', value: 'https://flagcdn.com/id.svg' },
      {
        label: 'Iran (Islamic Republic of)',
        value: 'https://flagcdn.com/ir.svg',
      },
      { label: 'Iraq', value: 'https://flagcdn.com/iq.svg' },
      { label: 'Ireland', value: 'https://flagcdn.com/ie.svg' },
      { label: 'Isle of Man', value: 'https://flagcdn.com/im.svg' },
      { label: 'Israel', value: 'https://flagcdn.com/il.svg' },
      { label: 'Italy', value: 'https://flagcdn.com/it.svg' },
      { label: 'Jamaica', value: 'https://flagcdn.com/jm.svg' },
      { label: 'Japan', value: 'https://flagcdn.com/jp.svg' },
      { label: 'Jersey', value: 'https://flagcdn.com/je.svg' },
      { label: 'Jordan', value: 'https://flagcdn.com/jo.svg' },
      { label: 'Kazakhstan', value: 'https://flagcdn.com/kz.svg' },
      { label: 'Kenya', value: 'https://flagcdn.com/ke.svg' },
      { label: 'Kiribati', value: 'https://flagcdn.com/ki.svg' },
      {
        label: "Korea (Democratic People's Republic of)",
        value: 'https://flagcdn.com/kp.svg',
      },
      { label: 'Korea, Republic of', value: 'https://flagcdn.com/kr.svg' },
      { label: 'Kuwait', value: 'https://flagcdn.com/kw.svg' },
      { label: 'Kyrgyzstan', value: 'https://flagcdn.com/kg.svg' },
      {
        label: "Lao People's Democratic Republic",
        value: 'https://flagcdn.com/la.svg',
      },
      { label: 'Latvia', value: 'https://flagcdn.com/lv.svg' },
      { label: 'Lebanon', value: 'https://flagcdn.com/lb.svg' },
      { label: 'Lesotho', value: 'https://flagcdn.com/ls.svg' },
      { label: 'Liberia', value: 'https://flagcdn.com/lr.svg' },
      { label: 'Libya', value: 'https://flagcdn.com/ly.svg' },
      { label: 'Liechtenstein', value: 'https://flagcdn.com/li.svg' },
      { label: 'Lithuania', value: 'https://flagcdn.com/lt.svg' },
      { label: 'Luxembourg', value: 'https://flagcdn.com/lu.svg' },
      { label: 'Macao', value: 'https://flagcdn.com/mo.svg' },
      { label: 'Madagascar', value: 'https://flagcdn.com/mg.svg' },
      { label: 'Malawi', value: 'https://flagcdn.com/mw.svg' },
      { label: 'Malaysia', value: 'https://flagcdn.com/my.svg' },
      { label: 'Maldives', value: 'https://flagcdn.com/mv.svg' },
      { label: 'Mali', value: 'https://flagcdn.com/ml.svg' },
      { label: 'Malta', value: 'https://flagcdn.com/mt.svg' },
      { label: 'Marshall Islands', value: 'https://flagcdn.com/mh.svg' },
      { label: 'Martinique', value: 'https://flagcdn.com/mq.svg' },
      { label: 'Mauritania', value: 'https://flagcdn.com/mr.svg' },
      { label: 'Mauritius', value: 'https://flagcdn.com/mu.svg' },
      { label: 'Mayotte', value: 'https://flagcdn.com/yt.svg' },
      { label: 'Mexico', value: 'https://flagcdn.com/mx.svg' },
      {
        label: 'Micronesia (Federated States of)',
        value: 'https://flagcdn.com/fm.svg',
      },
      { label: 'Moldova, Republic of', value: 'https://flagcdn.com/md.svg' },
      { label: 'Monaco', value: 'https://flagcdn.com/mc.svg' },
      { label: 'Mongolia', value: 'https://flagcdn.com/mn.svg' },
      { label: 'Montenegro', value: 'https://flagcdn.com/me.svg' },
      { label: 'Montserrat', value: 'https://flagcdn.com/ms.svg' },
      { label: 'Morocco', value: 'https://flagcdn.com/ma.svg' },
      { label: 'Mozambique', value: 'https://flagcdn.com/mz.svg' },
      { label: 'Myanmar', value: 'https://flagcdn.com/mm.svg' },
      { label: 'Namibia', value: 'https://flagcdn.com/na.svg' },
      { label: 'Nauru', value: 'https://flagcdn.com/nr.svg' },
      { label: 'Nepal', value: 'https://flagcdn.com/np.svg' },
      {
        label: 'Netherlands, Kingdom of the',
        value: 'https://flagcdn.com/nl.svg',
      },
      { label: 'New Caledonia', value: 'https://flagcdn.com/nc.svg' },
      { label: 'New Zealand', value: 'https://flagcdn.com/nz.svg' },
      { label: 'Nicaragua', value: 'https://flagcdn.com/ni.svg' },
      { label: 'Niger', value: 'https://flagcdn.com/ne.svg' },
      { label: 'Nigeria', value: 'https://flagcdn.com/ng.svg' },
      { label: 'Niue', value: 'https://flagcdn.com/nu.svg' },
      { label: 'Norfolk Island', value: 'https://flagcdn.com/nf.svg' },
      { label: 'North Macedonia', value: 'https://flagcdn.com/mk.svg' },
      { label: 'Northern Mariana Islands', value: 'https://flagcdn.com/mp.svg' },
      { label: 'Norway', value: 'https://flagcdn.com/no.svg' },
      { label: 'Oman', value: 'https://flagcdn.com/om.svg' },
      { label: 'Pakistan', value: 'https://flagcdn.com/pk.svg' },
      { label: 'Palau', value: 'https://flagcdn.com/pw.svg' },
      { label: 'Palestine, State of', value: 'https://flagcdn.com/ps.svg' },
      { label: 'Panama', value: 'https://flagcdn.com/pa.svg' },
      { label: 'Papua New Guinea', value: 'https://flagcdn.com/pg.svg' },
      { label: 'Paraguay', value: 'https://flagcdn.com/py.svg' },
      { label: 'Peru', value: 'https://flagcdn.com/pe.svg' },
      { label: 'Philippines', value: 'https://flagcdn.com/ph.svg' },
      { label: 'Pitcairn', value: 'https://flagcdn.com/pn.svg' },
      { label: 'Poland', value: 'https://flagcdn.com/pl.svg' },
      { label: 'Portugal', value: 'https://flagcdn.com/pt.svg' },
      { label: 'Puerto Rico', value: 'https://flagcdn.com/pr.svg' },
      { label: 'Qatar', value: 'https://flagcdn.com/qa.svg' },
      { label: 'Réunion', value: 'https://flagcdn.com/re.svg' },
      { label: 'Romania', value: 'https://flagcdn.com/ro.svg' },
      { label: 'Russian Federation', value: 'https://flagcdn.com/ru.svg' },
      { label: 'Rwanda', value: 'https://flagcdn.com/rw.svg' },
      { label: 'Saint Barthélemy', value: 'https://flagcdn.com/bl.svg' },
      {
        label: 'Saint Helena, Ascension and Tristan da Cunha',
        value: 'https://flagcdn.com/sh.svg',
      },
      { label: 'Saint Kitts and Nevis', value: 'https://flagcdn.com/kn.svg' },
      { label: 'Saint Lucia', value: 'https://flagcdn.com/lc.svg' },
      {
        label: 'Saint Martin (French part)',
        value: 'https://flagcdn.com/mf.svg',
      },
      { label: 'Saint Pierre and Miquelon', value: 'https://flagcdn.com/pm.svg' },
      {
        label: 'Saint Vincent and the Grenadines',
        value: 'https://flagcdn.com/vc.svg',
      },
      { label: 'Samoa', value: 'https://flagcdn.com/ws.svg' },
      { label: 'San Marino', value: 'https://flagcdn.com/sm.svg' },
      { label: 'Sao Tome and Principe', value: 'https://flagcdn.com/st.svg' },
      { label: 'Saudi Arabia', value: 'https://flagcdn.com/sa.svg' },
      { label: 'Senegal', value: 'https://flagcdn.com/sn.svg' },
      { label: 'Serbia', value: 'https://flagcdn.com/rs.svg' },
      { label: 'Seychelles', value: 'https://flagcdn.com/sc.svg' },
      { label: 'Sierra Leone', value: 'https://flagcdn.com/sl.svg' },
      { label: 'Singapore', value: 'https://flagcdn.com/sg.svg' },
      { label: 'Sint Maarten (Dutch part)', value: 'https://flagcdn.com/sx.svg' },
      { label: 'Slovakia', value: 'https://flagcdn.com/sk.svg' },
      { label: 'Slovenia', value: 'https://flagcdn.com/si.svg' },
      { label: 'Solomon Islands', value: 'https://flagcdn.com/sb.svg' },
      { label: 'Somalia', value: 'https://flagcdn.com/so.svg' },
      { label: 'South Africa', value: 'https://flagcdn.com/za.svg' },
      {
        label: 'South Georgia and the South Sandwich Islands',
        value: 'https://flagcdn.com/gs.svg',
      },
      { label: 'South Sudan', value: 'https://flagcdn.com/ss.svg' },
      { label: 'Spain', value: 'https://flagcdn.com/es.svg' },
      { label: 'Sri Lanka', value: 'https://flagcdn.com/lk.svg' },
      { label: 'Sudan', value: 'https://flagcdn.com/sd.svg' },
      { label: 'Suriname', value: 'https://flagcdn.com/sr.svg' },
      { label: 'Svalbard and Jan Mayen', value: 'https://flagcdn.com/sj.svg' },
      { label: 'Sweden', value: 'https://flagcdn.com/se.svg' },
      { label: 'Switzerland', value: 'https://flagcdn.com/ch.svg' },
      { label: 'Syrian Arab Republic', value: 'https://flagcdn.com/sy.svg' },
      { label: 'Taiwan, Province of China', value: 'https://flagcdn.com/tw.svg' },
      { label: 'Tajikistan', value: 'https://flagcdn.com/tj.svg' },
      {
        label: 'Tanzania, United Republic of',
        value: 'https://flagcdn.com/tz.svg',
      },
      { label: 'Thailand', value: 'https://flagcdn.com/th.svg' },
      { label: 'Timor-Leste', value: 'https://flagcdn.com/tl.svg' },
      { label: 'Togo', value: 'https://flagcdn.com/tg.svg' },
      { label: 'Tokelau', value: 'https://flagcdn.com/tk.svg' },
      { label: 'Tonga', value: 'https://flagcdn.com/to.svg' },
      { label: 'Trinidad and Tobago', value: 'https://flagcdn.com/tt.svg' },
      { label: 'Tunisia', value: 'https://flagcdn.com/tn.svg' },
      { label: 'Türkiye', value: 'https://flagcdn.com/tr.svg' },
      { label: 'Turkmenistan', value: 'https://flagcdn.com/tm.svg' },
      { label: 'Turks and Caicos Islands', value: 'https://flagcdn.com/tc.svg' },
      { label: 'Tuvalu', value: 'https://flagcdn.com/tv.svg' },
      { label: 'Uganda', value: 'https://flagcdn.com/ug.svg' },
      { label: 'Ukraine', value: 'https://flagcdn.com/ua.svg' },
      { label: 'United Arab Emirates', value: 'https://flagcdn.com/ae.svg' },
      {
        label: 'United Kingdom of Great Britain and Northern Ireland',
        value: 'https://flagcdn.com/gb.svg',
      },
      { label: 'United States of America', value: 'https://flagcdn.com/us.svg' },
      {
        label: 'United States Minor Outlying Islands',
        value: 'https://flagcdn.com/um.svg',
      },
      { label: 'Uruguay', value: 'https://flagcdn.com/uy.svg' },
      { label: 'Uzbekistan', value: 'https://flagcdn.com/uz.svg' },
      { label: 'Vanuatu', value: 'https://flagcdn.com/vu.svg' },
      {
        label: 'Venezuela (Bolivarian Republic of)',
        value: 'https://flagcdn.com/ve.svg',
      },
      { label: 'Viet Nam', value: 'https://flagcdn.com/vn.svg' },
      { label: 'Virgin Islands (British)', value: 'https://flagcdn.com/vg.svg' },
      { label: 'Virgin Islands (U.S.)', value: 'https://flagcdn.com/vi.svg' },
      { label: 'Wallis and Futuna', value: 'https://flagcdn.com/wf.svg' },
      { label: 'Western Sahara', value: 'https://flagcdn.com/eh.svg' },
      { label: 'Yemen', value: 'https://flagcdn.com/ye.svg' },
      { label: 'Zambia', value: 'https://flagcdn.com/zm.svg' },
      { label: 'Zimbabwe', value: 'https://flagcdn.com/zw.svg' },
    ];
  }